package typed

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strconv"
	"strings"
	"unicode"
)

type GenerateOptions struct {
	Package string
}

func Generate(namespaces []Namespace, options GenerateOptions) (map[string][]byte, error) {
	if options.Package == "" {
		return nil, errors.New("typed socket.io: output package is required")
	}
	client, server := &bytes.Buffer{}, &bytes.Buffer{}
	writeGoHeader(client, options.Package)
	writeGoHeader(server, options.Package)
	typescript, markdown := &bytes.Buffer{}, &bytes.Buffer{}
	markdown.WriteString("# Socket.IO 事件\n\n| Namespace | 事件 | 方向 | 请求 | ACK | 说明 |\n|---|---|---|---|---|---|\n")
	declared := make(map[reflect.Type]bool)
	for _, namespace := range namespaces {
		for _, definition := range namespace.Events {
			if definition.Name == "" || definition.RequestType == nil || definition.ResponseType == nil {
				return nil, errors.New("typed socket.io: invalid event definition")
			}
			writeTypeScriptType(typescript, definition.RequestType, declared)
			writeTypeScriptType(typescript, definition.ResponseType, declared)
			writeTypeScriptEvent(typescript, namespace.Name, &definition)
			writeClientWrapper(client, &definition)
			writeServerWrapper(server, &definition)
			fmt.Fprintf(markdown, "| `%s` | `%s` | %s | `%s` | `%s` | %s |\n",
				namespace.Name, definition.Name, definition.Direction,
				typeName(definition.RequestType), typeName(definition.ResponseType), definition.Description)
		}
	}
	clientSource, err := format.Source(client.Bytes())
	if err != nil {
		return nil, fmt.Errorf("typed socket.io: format client: %w", err)
	}
	serverSource, err := format.Source(server.Bytes())
	if err != nil {
		return nil, fmt.Errorf("typed socket.io: format server: %w", err)
	}
	return map[string][]byte{
		"socketio_client.gen.go": clientSource,
		"socketio_server.gen.go": serverSource,
		"socketio_events.gen.ts": typescript.Bytes(),
		"socketio_events.md":     markdown.Bytes(),
	}, nil
}

func WriteFiles(directory string, files map[string][]byte) error {
	if err := os.MkdirAll(directory, 0o755); err != nil {
		return err
	}
	names := make([]string, 0, len(files))
	for name := range files {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		if filepath.Base(name) != name {
			return fmt.Errorf("typed socket.io: invalid output filename %q", name)
		}
		if err := os.WriteFile(filepath.Join(directory, name), files[name], 0o644); err != nil {
			return err
		}
	}
	return nil
}

func writeGoHeader(buffer *bytes.Buffer, packageName string) {
	fmt.Fprintf(buffer, "// Code generated by socket.io/typed. DO NOT EDIT.\npackage %s\n\n", packageName)
	buffer.WriteString("import (\n\"context\"\nsockettyped \"github.com/aqcool/socket.io/typed/v4\"\n)\n\n")
	buffer.WriteString("var _ = context.Background\n\n")
}

func writeClientWrapper(buffer *bytes.Buffer, definition *Definition) {
	name := exportedName(definition.Name)
	request, response := goType(definition.RequestType), goType(definition.ResponseType)
	fmt.Fprintf(buffer, "var %sEvent = sockettyped.Event[%s, %s]{Name:%q, Direction:%q, Description:%q}\n",
		name, request, response, definition.Name, definition.Direction, definition.Description)
	switch definition.Direction {
	case ClientToServer, Bidirectional:
		if definition.ResponseType == reflect.TypeFor[NoAck]() {
			fmt.Fprintf(buffer, "func Emit%s(emitter sockettyped.Emitter, request %s) error { return sockettyped.Emit(emitter, %sEvent, request) }\n\n", name, request, name)
		} else {
			fmt.Fprintf(buffer, "func Emit%s(ctx context.Context, emitter sockettyped.Emitter, request %s) (%s,error) { return sockettyped.EmitAck(ctx, emitter, %sEvent, request) }\n\n", name, request, response, name)
		}
	case ServerToClient:
		if definition.ResponseType == reflect.TypeFor[NoAck]() {
			fmt.Fprintf(buffer, "func On%s(registrar sockettyped.Registrar, handler func(context.Context,%s) error) error { return sockettyped.On(registrar, %sEvent, handler) }\n\n", name, request, name)
		} else {
			fmt.Fprintf(buffer, "func Handle%s(registrar sockettyped.Registrar, handler func(context.Context,%s)(%s,error)) error { return sockettyped.Handle(registrar, %sEvent, handler) }\n\n", name, request, response, name)
		}
	}
}

func writeServerWrapper(buffer *bytes.Buffer, definition *Definition) {
	name := exportedName(definition.Name)
	request, response := goType(definition.RequestType), goType(definition.ResponseType)
	switch definition.Direction {
	case ClientToServer, Bidirectional:
		if definition.ResponseType == reflect.TypeFor[NoAck]() {
			fmt.Fprintf(buffer, "func On%s(registrar sockettyped.Registrar, handler func(context.Context,%s) error) error { return sockettyped.On(registrar, %sEvent, handler) }\n\n", name, request, name)
		} else {
			fmt.Fprintf(buffer, "func Handle%s(registrar sockettyped.Registrar, handler func(context.Context,%s)(%s,error)) error { return sockettyped.Handle(registrar, %sEvent, handler) }\n\n", name, request, response, name)
		}
	case ServerToClient:
		if definition.ResponseType == reflect.TypeFor[NoAck]() {
			fmt.Fprintf(buffer, "func Send%s(emitter sockettyped.Emitter, request %s) error { return sockettyped.Emit(emitter, %sEvent, request) }\n\n", name, request, name)
		} else {
			fmt.Fprintf(buffer, "func Send%s(ctx context.Context, emitter sockettyped.Emitter, request %s) (%s,error) { return sockettyped.EmitAck(ctx, emitter, %sEvent, request) }\n\n", name, request, response, name)
		}
	case ServerToServer:
		if definition.ResponseType == reflect.TypeFor[NoAck]() {
			fmt.Fprintf(buffer, "func Broadcast%s(emitter sockettyped.ServerSideEmitter, request %s) error { return sockettyped.ServerSideEmit(emitter, %sEvent, request) }\n\n", name, request, name)
		} else {
			fmt.Fprintf(buffer, "func Broadcast%s(ctx context.Context, emitter sockettyped.ServerSideEmitter, request %s) ([]%s,error) { return sockettyped.ServerSideEmitAck(ctx, emitter, %sEvent, request) }\n\n", name, request, response, name)
		}
	}
}

func writeTypeScriptEvent(buffer *bytes.Buffer, namespace string, definition *Definition) {
	fmt.Fprintf(buffer, "export type %sEvent = { namespace: %s; event: %s; request: %s; ack: %s };\n\n",
		exportedName(definition.Name), strconv.Quote(namespace), strconv.Quote(definition.Name),
		tsType(definition.RequestType), tsType(definition.ResponseType))
}

func writeTypeScriptType(buffer *bytes.Buffer, typ reflect.Type, declared map[reflect.Type]bool) {
	for typ.Kind() == reflect.Pointer {
		typ = typ.Elem()
	}
	if typ.Name() == "" || declared[typ] || typ == reflect.TypeFor[NoAck]() {
		return
	}
	declared[typ] = true
	if typ.Kind() != reflect.Struct {
		fmt.Fprintf(buffer, "export type %s = %s;\n\n", typ.Name(), tsUnderlying(typ))
		return
	}
	fmt.Fprintf(buffer, "export interface %s {\n", typ.Name())
	nested := make([]reflect.Type, 0, typ.NumField())
	for field := range typ.Fields() {
		if !field.IsExported() {
			continue
		}
		name, optional := jsonField(&field)
		if name == "-" {
			continue
		}
		fmt.Fprintf(buffer, "  %s%s: %s;\n", name, optional, tsType(field.Type))
		nested = append(nested, field.Type)
	}
	buffer.WriteString("}\n\n")
	for _, fieldType := range nested {
		writeTypeScriptType(buffer, fieldType, declared)
	}
}

func tsUnderlying(typ reflect.Type) string {
	return tsType(typ)
}

func tsType(typ reflect.Type) string {
	for typ.Kind() == reflect.Pointer {
		typ = typ.Elem()
	}
	if typ.Name() != "" {
		if typ == reflect.TypeFor[NoAck]() {
			return "void"
		}
		if typ.PkgPath() != "" {
			return typ.Name()
		}
	}
	switch typ.Kind() {
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Float32, reflect.Float64:
		return "number"
	case reflect.String:
		return "string"
	case reflect.Slice, reflect.Array:
		return tsType(typ.Elem()) + "[]"
	case reflect.Map:
		return "Record<string, " + tsType(typ.Elem()) + ">"
	case reflect.Interface:
		return "unknown"
	default:
		return "unknown"
	}
}

func goType(typ reflect.Type) string {
	if typ == reflect.TypeFor[NoAck]() {
		return "sockettyped.NoAck"
	}
	if typ.Name() != "" {
		return typ.Name()
	}
	switch typ.Kind() {
	case reflect.Pointer:
		return "*" + goType(typ.Elem())
	case reflect.Slice:
		return "[]" + goType(typ.Elem())
	case reflect.Array:
		return fmt.Sprintf("[%d]%s", typ.Len(), goType(typ.Elem()))
	case reflect.Map:
		return "map[" + goType(typ.Key()) + "]" + goType(typ.Elem())
	default:
		return typ.String()
	}
}

func typeName(typ reflect.Type) string {
	if typ == reflect.TypeFor[NoAck]() {
		return "-"
	}
	return goType(typ)
}

func exportedName(value string) string {
	parts := strings.FieldsFunc(value, func(r rune) bool { return !unicode.IsLetter(r) && !unicode.IsDigit(r) })
	var result strings.Builder
	for _, part := range parts {
		runes := []rune(part)
		if len(runes) == 0 {
			continue
		}
		runes[0] = unicode.ToUpper(runes[0])
		result.WriteString(string(runes))
	}
	if result.Len() == 0 {
		return "Event"
	}
	return result.String()
}

func jsonField(field *reflect.StructField) (string, string) {
	tag := strings.Split(field.Tag.Get("json"), ",")
	name := field.Name
	if len(tag) > 0 && tag[0] != "" {
		name = tag[0]
	}
	optional := ""
	for _, option := range tag[1:] {
		if option == "omitempty" || option == "omitzero" {
			optional = "?"
		}
	}
	return name, optional
}
